TRANSLATIONS = {
    "en": {
        "tracker": "Tracker",
        "history": "History",
        "settings": "Settings",
        
        "lens": "Lens",
        "track": "Track",
        "start_session": "Start Session",
        "stop_session": "Stop Session",
        "daily_wear_time": "DAILY WEAR TIME",
        "replacement": "REPLACEMENT",
        "days_left": "days left",
        "active": "ACTIVE",
        "paused": "PAUSED",
        "replace": "Replace",
        "start_tracking": "Start\nTracking",
        "health_tip": "HEALTH TIP",
        "limit_exceeded": "LIMIT EXCEEDED",
        "health_tip_body": "Keep your lens case clean. Rinse it with fresh solution (not water) and let it air dry upside down every day.",
        "health_tip_wear_exceeded": "You have worn your lenses for {hours}+ hours today. Please remove them immediately to rest your eyes.",
        "health_tip_days_exceeded": "Your lenses have reached their replacement date. Please replace them now to protect your eye health.",
        "stop_session_title": "Stop Session?",
        "stop_session_content": "Are you sure you want to stop the current session?",
        "yes": "Yes",
        "no": "No",
        "replace_dialog_title": "Replace Lenses?",
        "replace_dialog_content": "Are you sure you want to replace your current lenses and reset the timer?",
        "ten_hours_snack": "You have been wearing lenses for 10 hours! Time to rest.",

        "history_title": "History",
        "history_subtitle": "Recent usage logs",
        "no_sessions": "No sessions yet",
        "no_sessions_desc": "Your daily wear logs will appear here\nafter you complete a session.",

        "lens_profile": "Lens Profile",
        "max_wear_duration": "Max Wear Duration",
        "current_lens_start": "Current Lens Start",
        "select_lens_duration": "Select Lens Duration",
        "days": "days",
        "days_short": "Days",
        "not_started": "Not Started",
        "close": "Close",
        "done": "Done",
        
        "notifications": "Notifications",
        "daily_reminder": "Daily Reminder",
        "replacement_alert": "Replacement Alert",
        
        "appearance": "Appearance",
        "theme": "Theme",
        "dark": "Dark",
        "light": "Light",
        "accent_color": "Accent Color",
        "language": "Language",
        "choose_accent": "Choose Accent Color",
        "select_palette": "Select a color palette:",
        "select_language": "Select Language",
        
        "privacy_data": "Privacy & Data",
        "settings_title": "Settings",
        "settings_desc": "Customize your experience",
        
        "monday": "Monday", "tuesday": "Tuesday", "wednesday": "Wednesday", "thursday": "Thursday", "friday": "Friday", "saturday": "Saturday", "sunday": "Sunday",
        "january": "January", "february": "February", "march": "March", "april": "April", "may": "May", "june": "June", "july": "July", "august": "August", "september": "September", "october": "October", "november": "November", "december": "December",
    },
    "ru": {
        "tracker": "Трекер",
        "history": "История",
        "settings": "Настройки",
        
        "lens": "Lens",
        "track": "Track",
        "start_session": "Начать",
        "stop_session": "Завершить",
        "daily_wear_time": "ВРЕМЯ НОШЕНИЯ",
        "replacement": "ЗАМЕНА",
        "days_left": "дней осталось",
        "active": "АКТИВНО",
        "paused": "ПАУЗА",
        "replace": "Заменить",
        "start_tracking": "Начать\nТрекинг",
        "health_tip": "СОВЕТ ЗДОРОВЬЯ",
        "limit_exceeded": "ЛИМИТ ПРЕВЫШЕН",
        "health_tip_body": "Держите контейнер для линз в чистоте. Промывайте его свежим раствором (не водой) и сушите на воздухе перевернутым каждый день.",
        "health_tip_wear_exceeded": "Вы носите линзы уже более {hours} часов. Пожалуйста, снимите их немедленно, чтобы дать глазам отдохнуть.",
        "health_tip_days_exceeded": "Ваши линзы достигли срока замены. Пожалуйста, замените их сейчас для защиты здоровья глаз.",
        "stop_session_title": "Завершить сеанс?",
        "stop_session_content": "Вы уверены, что хотите завершить текущий сеанс ношения?",
        "yes": "Да",
        "no": "Нет",
        "replace_dialog_title": "Заменить линзы?",
        "replace_dialog_content": "Вы уверены, что хотите заменить текущие линзы и сбросить таймер?",
        "ten_hours_snack": "Вы носите линзы уже 10 часов! Время отдохнуть.",

        "history_title": "История",
        "history_subtitle": "Недавние сеансы ношения",
        "no_sessions": "Пока нет сеансов",
        "no_sessions_desc": "Ваша история ношения линз появится здесь\nпосле завершения первого сеанса.",

        "lens_profile": "Профиль линз",
        "max_wear_duration": "Частота замены",
        "current_lens_start": "Текущие надеты",
        "select_lens_duration": "Выберите срок ношения",
        "days": "дней",
        "days_short": "Дней",
        "not_started": "Не начато",
        "close": "Закрыть",
        "done": "Готово",

        "notifications": "Уведомления",
        "daily_reminder": "Ежедневное напоминание",
        "replacement_alert": "Напоминание о замене",

        "appearance": "Оформление",
        "theme": "Тема",
        "dark": "Темная",
        "light": "Светлая",
        "accent_color": "Цвет акцента",
        "language": "Язык",
        "choose_accent": "Выберите цвет акцента",
        "select_palette": "Выберите палитру цветов:",
        "select_language": "Выберите язык",

        "privacy_data": "Конфиденциальность",
        "settings_title": "Настройки",
        "settings_desc": "Настройте приложение под себя",
        
        "monday": "Понедельник", "tuesday": "Вторник", "wednesday": "Среда", "thursday": "Четверг", "friday": "Пятница", "saturday": "Суббота", "sunday": "Воскресенье",
        "january": "Января", "february": "Февраля", "march": "Марта", "april": "Апреля", "may": "Мая", "june": "Июня", "july": "Июля", "august": "Августа", "september": "Сентября", "october": "Октября", "november": "Ноября", "december": "Декабря",
    },
    "fr": {
        "tracker": "Suivi",
        "history": "Historique",
        "settings": "Paramètres",
        
        "lens": "Lens",
        "track": "Track",
        "start_session": "Démarrer",
        "stop_session": "Arrêter",
        "daily_wear_time": "TEMPS DE PORT JOURNALIER",
        "replacement": "REMPLACEMENT",
        "days_left": "jours restants",
        "active": "ACTIF",
        "paused": "EN PAUSE",
        "replace": "Remplacer",
        "start_tracking": "Démarrer\nSuivi",
        "health_tip": "CONSEIL SANTÉ",
        "limit_exceeded": "LIMITE DÉPASSÉE",
        "health_tip_body": "Gardez votre étui à lentilles propre. Rincez-le avec une solution fraîche (pas d'eau) et laissez-le sécher à l'air libre à l'envers tous les jours.",
        "health_tip_wear_exceeded": "Vous avez porté vos lentilles pendant plus de {hours} heures aujourd'hui. Veuillez les retirer immédiatement pour reposer vos yeux.",
        "health_tip_days_exceeded": "Vos lentilles ont atteint leur date de remplacement. Veuillez les remplacer maintenant pour protéger la santé de vos yeux.",
        "stop_session_title": "Arrêter la session?",
        "stop_session_content": "Êtes-vous sûr de vouloir arrêter la session en cours?",
        "yes": "Oui",
        "no": "Non",
        "replace_dialog_title": "Remplacer les lentilles?",
        "replace_dialog_content": "Êtes-vous sûr de vouloir remplacer vos lentilles actuelles et réinitialiser le minuteur?",
        "ten_hours_snack": "Vous portez des lentilles depuis 10 heures ! Il est temps de vous reposer.",

        "history_title": "Historique",
        "history_subtitle": "Journaux d'utilisation",
        "no_sessions": "Aucune session",
        "no_sessions_desc": "Vos journaux de port quotidien apparaîtront ici\naprès avoir terminé une session.",

        "lens_profile": "Profil de lentille",
        "max_wear_duration": "Durée de port max",
        "current_lens_start": "Mis le",
        "select_lens_duration": "Sélectionner la durée",
        "days": "jours",
        "days_short": "Jours",
        "not_started": "Non démarré",
        "close": "Fermer",
        "done": "Terminé",

        "notifications": "Notifications",
        "daily_reminder": "Rappel quotidien",
        "replacement_alert": "Alerte de remplacement",

        "appearance": "Apparence",
        "theme": "Thème",
        "dark": "Sombre",
        "light": "Clair",
        "accent_color": "Couleur d'accent",
        "language": "Langue",
        "choose_accent": "Choisir la couleur d'accent",
        "select_palette": "Sélectionnez une palette :",
        "select_language": "Sélectionner la langue",

        "privacy_data": "Confidentialité",
        "settings_title": "Paramètres",
        "settings_desc": "Personnalisez votre expérience",
        
        "monday": "Lundi", "tuesday": "Mardi", "wednesday": "Mercredi", "thursday": "Jeudi", "friday": "Vendredi", "saturday": "Samedi", "sunday": "Dimanche",
        "january": "Janvier", "february": "Février", "march": "Mars", "april": "Avril", "may": "Mai", "june": "Juin", "july": "Juillet", "august": "Août", "september": "Septembre", "october": "Octobre", "november": "Novembre", "december": "Décembre",
    },
    "de": {
        "tracker": "Tracker",
        "history": "Verlauf",
        "settings": "Einstellungen",
        
        "lens": "Lens",
        "track": "Track",
        "start_session": "Starten",
        "stop_session": "Beenden",
        "daily_wear_time": "TÄGLICHE TRAGEZEIT",
        "replacement": "AUSTAUSCH",
        "days_left": "tage übrig",
        "active": "AKTIV",
        "paused": "PAUSIERT",
        "replace": "Ersetzen",
        "start_tracking": "Tracking\nstarten",
        "health_tip": "GESUNDHEITSTIPP",
        "limit_exceeded": "LIMIT ÜBERSCHRITTEN",
        "health_tip_body": "Halten Sie Ihren Linsenbehälter sauber. Spülen Sie ihn täglich mit frischer Lösung (kein Wasser) und lassen Sie ihn an der Luft umgedreht trocknen.",
        "health_tip_wear_exceeded": "Sie haben Ihre Linsen heute mehr als {hours} Stunden getragen. Bitte entfernen Sie diese sofort, um Ihre Augen auszuruhen.",
        "health_tip_days_exceeded": "Ihre Linsen haben ihr Austauschdatum erreicht. Bitte ersetzen Sie sie jetzt, um Ihre Augengesundheit zu schützen.",
        "stop_session_title": "Sitzung beenden?",
        "stop_session_content": "Sind Sie sicher, dass Sie die aktuelle Sitzung beenden möchten?",
        "yes": "Ja",
        "no": "Nein",
        "replace_dialog_title": "Linsen ersetzen?",
        "replace_dialog_content": "Sind Sie sicher, dass Sie Ihre aktuellen Linsen ersetzen und den Timer zurücksetzen möchten?",
        "ten_hours_snack": "Sie tragen die Linsen seit 10 Stunden! Zeit sich auszuruhen.",

        "history_title": "Verlauf",
        "history_subtitle": "Letzte Nutzungsprotokolle",
        "no_sessions": "Noch keine Sitzungen",
        "no_sessions_desc": "Ihre täglichen Trageprotokolle werden hier angezeigt,\nnachdem Sie eine Sitzung abgeschlossen haben.",

        "lens_profile": "Linsenprofil",
        "max_wear_duration": "Maximale Tragedauer",
        "current_lens_start": "Derzeitig eingesetzt",
        "select_lens_duration": "Dauer auswählen",
        "days": "Tage",
        "days_short": "Tage",
        "not_started": "Nicht gestartet",
        "close": "Schließen",
        "done": "Fertig",

        "notifications": "Benachrichtigungen",
        "daily_reminder": "Tägliche Erinnerung",
        "replacement_alert": "Austauschalarm",

        "appearance": "Erscheinungsbild",
        "theme": "Design",
        "dark": "Dunkel",
        "light": "Hell",
        "accent_color": "Akzentfarbe",
        "language": "Sprache",
        "choose_accent": "Akzentfarbe wählen",
        "select_palette": "Wählen Sie eine Farbpalette:",
        "select_language": "Sprache auswählen",

        "privacy_data": "Datenschutz & Daten",
        "settings_title": "Einstellungen",
        "settings_desc": "Passen Sie Ihr Erlebnis an",
        
        "monday": "Montag", "tuesday": "Dienstag", "wednesday": "Mittwoch", "thursday": "Donnerstag", "friday": "Freitag", "saturday": "Samstag", "sunday": "Sonntag",
        "january": "Januar", "february": "Februar", "march": "März", "april": "April", "may": "Mai", "june": "Juni", "july": "Juli", "august": "August", "september": "September", "october": "Oktober", "november": "November", "december": "Dezember",
    }
}

class Locales:
    current_lang = "en"

    @classmethod
    def get(cls, key: str, **kwargs):
        text = TRANSLATIONS.get(cls.current_lang, TRANSLATIONS["en"]).get(key, key)
        if kwargs:
            return text.format(**kwargs)
        return text

def t(key: str, **kwargs):
    return Locales.get(key, **kwargs)
